"""Add to Claim model attributes description, date, currency, expenseType, etc.

Revision ID: fd94c901b988
Revises: d9c1f53e972c
Create Date: 2024-04-01 13:29:09.244569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd94c901b988'
down_revision = 'd9c1f53e972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('expenseType', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('expenseType')
        batch_op.drop_column('currency')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
